description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "game"
publish_to: "none"
dependencies: 
  angel_common: "^1.0.0"
  angel_configuration: "^1.0.0"
  angel_multiserver: "^1.0.0"
  angel_relations: ^1.0.0
  angel_security: ^1.0.0
  angel_websocket: ^1.0.0
  owl: ^0.1.1
  phaser: ^2.6.2
dev_dependencies: 
  browser: ^0.10.0
  build_runner: ^0.3.0
  dart_to_js_script_rewriter: ^1.0.0
  grinder: "^0.8.0"
  http: "^0.11.3"
  owl_codegen: ^0.1.1
  test: "^0.12.13"
environment: 
  sdk: ">=1.19.0"
transformers: 
  - "angel_configuration"
  - dart_to_js_script_rewriter
